services:
  server:
    image: allesbot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/db
    env_file: .env
    develop:
      watch:
        - action: rebuild
          path: .
